### ISSUE TITLE
TT Smokey Quartz cannot be used with Botania Tiara

### ISSUE THREAD

**Issue by FakoTheGreat** [TPPIDev/TestPackPleaseIgnore2#8]
As title says.  The only version of Smokey Quartz currently available in the pack is from Thaumic Tinkerer, which is not accepted as a valid version of quartz when changing wing types with the Flugel Tiara from Botania.

**Comment by esKaayY** [comment]
Was this ever fixed internally/externally?

**Comment by esKaayY** [comment]
Rapthera confirmed this is no longer an issue with whatever we did. Closing

**Comment by TehNut** [comment]
We fixed this with a Minetweaker script that allows conversions between the two, IIRC.

**Comment by FakoTheGreat** [comment]
Nut is correct, the 'fix' is nothing more than a MT script with a shapeless recipe to swap between the two versions. The issue still exists, after a fashion.

**Comment by TehNut** [comment]
We'll fix this with TPPITweaks. Until it's actually fixed, at least.

**Comment by FakoTheGreat** [comment]
Fixed in latest TPPI-Tweaks.
